# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e1d9f92d823182fefe1cc0629d13377acef397d3efaa01cb3b8e947f9f3eea2aca86e726e003685d3219d9e2e661b3277de12d762c228415856dc8b039a9ad6

test:
  secret_key_base: f2f0ffbb7460de7ff3f5d38add8f476769824a5f96f845597dfa7de3153257b52462145546453a35015810d69916418d8c00fa392ef1800bc3de7cfb4f254398

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
